name: Mobile tests

on:
  push:
  workflow_dispatch:

jobs:
  harmonix-mobile:
    name: Build and test harmonix_mobile
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SQLite3
        run: |
          brew install sqlite3
          cp /opt/homebrew/opt/sqlite/bin/sqlite3 ./libsqlite3.dylib
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          cache: true
      - run: flutter pub get
      - run: dart ./scripts/init_powersync_core_binary.dart
      - run: flutter test --dart-define SQLITE_BIN=$(which sqlite3)
