name: Mobile tests

on:
  push:
  workflow_dispatch:

jobs:
  harmonix-mobile:
    name: Build and test harmonix_mobile
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SQLite3
        run: |
          brew install sqlite3
        shell: zsh
      - name: Update sqlite3 path
        run: |
          echo 'export PATH="/opt/homebrew/opt/sqlite/bin:$PATH"' >> ~/.zshrc
          cat ~/.zshrc
          which sqlite3
        shell: zsh
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          cache: true
      - run: flutter pub get
        shell: zsh
      - run: dart ./scripts/init_powersync_core_binary.dart
        shell: zsh
      - run: flutter test --dart-define SQLITE_BIN=$(which sqlite3)
        shell: zsh
